### PR TITLE
Component simulator

### PR DESCRIPTION
**Pull request by Deltaphish**
I have added support for Junit & JavaDoc in the maven config.
I have also created and tested a foundation for the logic simulation system.

### CODE REVIEW

**Comment by 89netraM** [comment]
Are the components limited to only receive from one output for each input? 

Can the components have multiple outputs?

**Comment by Deltaphish** [comment]
There is nothing in the current implementation that limits a component from receiving data from multiple components into the same input. The most recent value that reaches the input is the one used. I figured that an unintentional 2 outputs 1 input scenario should be handled by a higher level ( Blueprint )

The current implementation does not support multiple outputs but should the need arise it would be easy to add. I could add it now, but since only high level components/blueprints would need them, I figure keep it simple until we need it.

**Comment by 89netraM** [comment]
How would the blueprint prevent 2 outputs to 1 input? Should all connections be made by a blueprint class? I feel like the components/connections should handle that themselves somehow.

Another thing. Can we get the value from a component with first sending an update to it? I saw the Output class, but it said it's only for debugging. Could this functionality not be useful other times too?

**Comment by Deltaphish** [comment]
While designing the components i thinking there was going to be a intermittent layer or wrapper so that classes depending on connecting components would not be dependent on the implementation of the connection.

What i meant with that a blueprint system could prevent 2 outputs to an input was that it could keep track of connections and safely disconnect and connect based on input from the controller.The actual implementation of the connection being handled by the Components, just that the blueprint makes sure the connections make sense. Seeing that the blueprint class would just be a container for components(since all simulation is happening in the Component class), saying that it could also sanity check the connection between components given by the controller is not a stretch.

A lucky break for us is that all java arrays are zero initialized so before any updates the inputs and outputs  of all nodes will be zero. We could re-call the update on all input components every time a new component is added, but that can come later when we tackle the "Pallet" of components for the ui.

Regarding the output class, while it's very useful for debugging and writing test, It can have a varying amount of inputs, making it a bother when creating a visual representation. We should create more dedicated "output" style components for the actual program. I should probably rename it to debugOutput or something and create a ledOutput or a hexOutput for production.

**Pull request merged**
